version: "3.9"

services:
  fastapi:
    build: src
    command: bash -c "python -m uvicorn app:app --reload --host 0.0.0.0 --port 8000"
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app
    depends_on:
      - db
      - kafka
    env_file:
      - env/backends.env
      - env/twitch.env
      - env/broker.env
    networks:
      - botnet
  fastapi_parser:
    build: src
    command: bash -c "python -m uvicorn app:app --reload --host 0.0.0.0 --port 8001"
    ports:
      - "8001:8001"
    volumes:
      - ./src:/app
    depends_on:
      - db
      - kafka
    env_file:
      - env/backends.env
      - env/twitch.env
      - env/broker.env
    networks:
      - botnet
  db:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
    networks:
      - botnet
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    hostname: zookeeper
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - botnet
  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://kafka:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
    networks:
      - botnet
  broker:
    build: broker
    command: bash -c "python broker.py"
    env_file:
      - env/backends.env
      - env/broker.env
    volumes:
      - ./broker:/app
    depends_on:
      - kafka
    networks:
      - botnet
  redis:
    image: redis:alpine
    container_name: redis
    hostname: redis
    ports:
      - "6379:6379"
    restart: always
    networks:
      - botnet

networks:
  botnet:

